### ISSUE TITLE
Do not leak key.pem and cert.pem

### ISSUE THREAD

**Issue by masayag** [il-blood-donation-info/blood-donation-backend#37]
See https://github.com/il-blood-donation-info/blood-donation-backend/blob/main/cmd/server/Dockerfile#L24

```
# FIXME: This makes the secret `key.pem` also part of the image; uploading the image anywhere would leak it!
# FIXME: any prior `cert.pem` & `key.pem` you had in current dir are *also* leaked in the COPY layer.
```

**Comment by cben** [comment]
Can we ignore this and get real certs #32 instead?

We'll still need some kind of setup for local dev. Let's Encrypt [won't mint localhost certs](https://letsencrypt.org/docs/certificates-for-localhost/) (there are tricky ways with DNS but not worth the trouble).  I think self-signed + `curl --insecure` is good enough.
Ideally create cert outside image and pass into container by mount/env var, but low priority.

**Comment by masayag** [comment]
sure. closed.
